name: Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Change this to your PHP version

    - name: Install Dependencies
      run: composer install

    - name: Run Syntax Check
      run: php -l index.php  # Adjust this command based on your project structure

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0     
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh u-220098548@cs2410-web01pvm.aston.ac.uk 'cd ~/public_html && git pull origin main'
